name: Trendify
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider:
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  animate_do: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/hii.png
    - assets/viewProduct.png
    - assets/test.png
    - assets/make_payment.png
    - assets/order.png
    - assets/intro.jpg
    - assets/profile.jpg
    - assets/beauty.jpeg
    - assets/fashion.jpg
    - assets/kids.jpeg
    - assets/mens.jpeg
    - assets/womens.jpeg
    - assets/offer1.jpg
    - assets/offer2.jpg
    - assets/offer3.jpg
    - assets/card.png
    - assets/p1.avif
    - assets/p2.jpg
    - assets/p3.jpg
    - assets/p4.jpg
    - assets/p5.jpg
    - assets/p6.jpg
    - assets/sp.jpg
    - assets/test.jpg
    - assets/choose.json
    - assets/payment.json
    - assets/order.json
    - assets/p.json
    - assets/c.json
    - assets/o.json

flutter_native_splash:
  color: "#FFFFFF"
  # background_image: "assets/background.png"
  image: assets/sp.jpg  # Make sure this image exists in your assets
  android: true
  ios: true
  web: true

  # Optional Android 12+ customization
  android_12:
    color: "#000000"
    image: assets/sp.jpg

  # Optional dark mode customization
  #color_dark: "#121212"
  #image_dark: assets/splash-dark.png
